#!/bin/bash

# ensure commits are prefixed with a module

commitFile="$1"

main () {
	if ! egrep '(^consumer:|^entity-store:|^host:|^message-store:|^messaging:|^package:|^runner:|^tools:)' "$commitFile"; then
		echo "ERROR: missing acceptable prefix (like message-store:)"
		exit 1
	fi
}

main
