#!/bin/bash

# ensure commits are prefixed with a module

commitFile="$1"

main () {
	if ! egrep '(^benchmark:|^consumer:|^errors:|^entity-projection:|^entity-store:|^host:|^logging:|^message-store:|^messaging:|^package:|^postgres-gateway:|^retry:|^runner:|^tools:)' "$commitFile"; then
		echo "ERROR: missing acceptable prefix (like message-store:)"
		exit 1
	fi
}

main
